// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbP-YeVyEUr7Ff2mfIBn3cDQ4x0kZ9AvE',
    appId: '1:1079923136353:web:8a09692e32873f813dd720',
    messagingSenderId: '1079923136353',
    projectId: 'travelers-app-flutter',
    authDomain: 'travelers-app-flutter.firebaseapp.com',
    storageBucket: 'travelers-app-flutter.firebasestorage.app',
    measurementId: 'G-BS4HZPP1K0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoqqK9UnLeWMmMwfTvRbxsM3hnJHbD3qo',
    appId: '1:1079923136353:android:3654e9e7fbe05e2c3dd720',
    messagingSenderId: '1079923136353',
    projectId: 'travelers-app-flutter',
    storageBucket: 'travelers-app-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUOHiYMY1Xa8RJGXwCcHBHG5mT_xGLdtY',
    appId: '1:1079923136353:ios:6895a592534bb4373dd720',
    messagingSenderId: '1079923136353',
    projectId: 'travelers-app-flutter',
    storageBucket: 'travelers-app-flutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterTravelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUOHiYMY1Xa8RJGXwCcHBHG5mT_xGLdtY',
    appId: '1:1079923136353:ios:6895a592534bb4373dd720',
    messagingSenderId: '1079923136353',
    projectId: 'travelers-app-flutter',
    storageBucket: 'travelers-app-flutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterTravelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbP-YeVyEUr7Ff2mfIBn3cDQ4x0kZ9AvE',
    appId: '1:1079923136353:web:9ff5d4a411be66b93dd720',
    messagingSenderId: '1079923136353',
    projectId: 'travelers-app-flutter',
    authDomain: 'travelers-app-flutter.firebaseapp.com',
    storageBucket: 'travelers-app-flutter.firebasestorage.app',
    measurementId: 'G-K3CYW1VJ85',
  );
}
